[F-1] ats-faisal
ZDZD-S/AI-trainees pull request #3
Opened 2024-03-14 09:02 UTC by FAISAL-K-ALOTAIBI

new code

2024-03-17 08:51 UTC, XMjeedX approved these changes

2024-03-17 09:11 UTC, ZDZD-S approved these changes

2024-03-17 09:18 UTC, MohammadModallalBloovo requested changes

2024-03-17 09:18 UTC, MohammadModallalBloovo commented on ATS(faisal)/ats.py
> +CSV_FILE = 'jobs.csv'
This should be input from user, or add it to "utils/constants.py" file

2024-03-17 09:18 UTC, MohammadModallalBloovo commented on ATS(faisal)/ats.py
> +# Create CSV file if it doesn't exist
We need class for file managment

2024-03-17 09:18 UTC, MohammadModallalBloovo commented on ATS(faisal)/ats.py
> +def list_candidate():
Need class for candidates functions

2024-03-17 09:18 UTC, MohammadModallalBloovo commented on ATS(faisal)/ats.py
> +def list_jobs():
Need class for jobs functions

2024-03-17 09:18 UTC, MohammadModallalBloovo commented on ATS(faisal)/ats.py
> +if not os.path.exists(CSV_FILE):
no need to check, you can add them to "csv/jobs.csv"

2024-03-17 09:18 UTC, MohammadModallalBloovo commented on ATS(faisal)/ats.py
> +        if choice == '1':
use python Enum, instead of direct numbers "1"

2024-03-17 09:18 UTC, MohammadModallalBloovo commented on ATS(faisal)/jobs.csv
> +suply performance ,respancpol for the suply .
This file should be empty

2024-03-18 10:37 UTC, MohammadModallalBloovo commented on ATS(faisal)/ats.py
> +import csv
requirements.txt
.gitignore
errors.py
constants.py
slack.py

2024-03-18 10:39 UTC, MohammadModallalBloovo commented on ATS(faisal)/ats.py
> +import csv
slack webhook

2024-03-30 21:26 UTC, closed without merging